### ISSUE TITLE
Filter Request: limit

### ISSUE THREAD

**Issue by joswr1ght** [endgameinc/eql#2]
Request an additional filter type of `limit` to limit the number of records returned from a query. 

```
$ eql query -f my-sysmon-data.json 'ParentImage != null | limit 1' | jq
```

This would be comparable to the `LIMIT` keyword in SQL, returning only the top _N_ records returned by the query. This is useful for getting a handle on the structure and format of the data that the analyst is working with.

**Comment by rw-access** [comment]
Hey @joswr1ght, you can use the `head` and `tail` pipes for returning only the first N or last N respectively.

https://eql.readthedocs.io/en/latest/query-guide/pipes.html#head

**Comment by joswr1ght** [comment]
True, but those work on line count, not JSON object count. Also, if there is an interactive query interface for `eql` (e.g. a `sql> ` SQLite3-like interface) then we lose integration with shell commands. Plus, `limit` would be platform-agnostic.

**Comment by joswr1ght** [comment]
It's also a nice nod to people with SQL experience working on transitioning what they already understand to working with EQL.

**Comment by rw-access** [comment]
So those pipes aren't line-based, they are actually event based and built into EQL directly, so they are part of the query itself. 
Try this
```console
$ eql query -f my-sysmon-data.json 'ParentImage != null | head 1' | jq
```

**Comment by joswr1ght** [comment]
This is just what I wanted, I incorrectly assumed _shell_ `head` and `tail`. Thank you!
